name: Auto Deployment To Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 5965 -H 89.117.36.103 >> ~/.ssh/known_hosts

    - name: Set Up .env.local File
      env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: "https://dev.pulisync.xyz"
          NEXT_PUBLIC_API_URL: "https://api.pulisync.xyz/api/v1"
      run: |
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env.local
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env.local
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env.local

    - name: Upload .env to Server
      run: |
        scp -P 5965 .env.local pulikids@89.117.36.103:/home/pulikids/pulisync-frontend/.env.local

    - name: Deploy to Server
      run: |
        ssh pulikids@89.117.36.103 -p 5965 << EOF
          cd /home/pulikids/pulisync-frontend
          git pull origin main
          docker compose down --remove-orphans
          docker compose build --no-cache
          docker compose up -d
        EOF
